"""Add daily_schedules table

Revision ID: fc6c49d6dd98
Revises: 
Create Date: 2026-02-16 01:27:00.962229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6c49d6dd98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_label', sa.String(length=10), nullable=False),
    sa.Column('icon_class', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_schedules')
    # ### end Alembic commands ###
